# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df2ec463f802c43a9b2c8f9f31a338b27b24b46f03ca3a39cf481f1077f94e27af96c8b3df445c44dcc7b0d3bebe4b40a7542d910b6e8601fa4acdb22aeaf021

test:
  secret_key_base: 4a99bef91f3294f6cfe28119fe40900681829d901a9896642d84e4ff51d0858019654af6ce16458df760cdeb20f5477cecb64ee972936d2b43f60b1a0dad4aa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
